---
title: "Graphical Display via Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(plotly)
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

data("rest_inspec")
```

Go back to the [homepage](index.html)

Column {data-width=650}
-----------------------------------------------------------------------

### Box Plot

```{r}
rest_box =
  rest_inspec |>
  drop_na() |>
  filter(
    boro == "Queens"
  ) 
```

```{r}
rest_box |> 
  plot_ly(y = ~score, x = ~cuisine_description, color = ~cuisine_description, type = "box", colors = "viridis") 
```



Column {data-width=350}
-----------------------------------------------------------------------
### Scatter Plot


```{r}
rest_scatter=
  rest_inspec |> 
  drop_na() |> 
  filter(
    boro == "Manhattan",
    score >= 20
    ) 
```

```{r}
rest_scatter |> 
  plot_ly(
    x = ~latitude, y = ~longitude, type = "scatter", mode = "markers",
    color = ~score, alpha = 0.5)
```



### Bar Plot
```{r}
rest_bar = 
  rest_inspec |>
  drop_na() |>
  filter(
    boro == "Brooklyn"
  ) 
```

```{r}
rest_bar |> 
  count(grade) |> 
  mutate(grade = fct_reorder(grade, n)) |> 
  plot_ly(x = ~grade, y = ~n, color = ~grade, type = "bar", colors = "viridis")
```





